# Generated by Django 3.1.2 on 2020-10-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.IntegerField()),
                ('student_class', models.CharField(default='III-D', max_length=255)),
                ('student_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sc', models.CharField(max_length=10)),
                ('lang', models.CharField(max_length=10)),
                ('lit', models.CharField(max_length=10)),
                ('hindi', models.CharField(max_length=10)),
                ('ssc', models.CharField(max_length=10)),
                ('maths', models.CharField(max_length=10)),
                ('gsc', models.CharField(max_length=10)),
                ('computer', models.CharField(max_length=10)),
                ('gk', models.CharField(max_length=10)),
                ('drawing', models.CharField(max_length=10)),
                ('writing', models.CharField(max_length=10)),
                ('recite', models.CharField(max_length=10)),
                ('reading', models.CharField(max_length=10)),
                ('story_telling', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.student')),
            ],
        ),
    ]
